# Nombre y configuración general de la aplicación
app:
  nombre: Form Auto Filler # cambiar el nombre despues
  idioma: es
  autor: TuNombre
  version: 1.0.0
  output_dir: ./reportes
  logs_dir: ./logs

# Configuración de Selenium
selenium:
  navegador: chrome
  headless: false       # true = sin ventana visible
  timeout: 10           # segundos de espera para elementos
  maximizar: true
  url_formulario: "https://demoqa.com/text-box"

# Formularios disponibles
formulario:
  activo: contacto      # nombre clave del formulario activo
  plantillas:
    contacto: ./config/schema_contacto.yaml
    registro: ./config/schema_registro.yaml

# Archivos por defecto
archivos:
  datos_entrada: ./data/datos.xlsx
  reporte_salida: ./reportes/reporte_validacion.xlsx

# UI
interfaz:
  tema: claro
  ancho_ventana: 800
  alto_ventana: 600