# Nombre y configuración general de la aplicación
app:
  nombre: Form Auto Filler # cambiar el nombre despues
  idioma: es
  autor: TuNombre
  version: 1.0.0
  output_dir: ./reportes
  logs_dir: ./logs

# Configuración de Selenium
selenium:
  navegador: chrome
  headless: false       # true = sin ventana visible
  timeout: 10           # segundos de espera para elementos
  maximizar: true
  url_formulario: "https://demoqa.com/text-box"

# Configuración de Validación
validacion:
  archivo_excel: "datos.xlsx"
  campos:
    nombre:
      tipo: str
      obligatorio: true
    email:
      tipo: str
      obligatorio: true
      regex: '^\S+@\S+\.\S+$'
    dir0:
      tipo: str
      obligatorio: true
    dir1:
      tipo: str
      obligatorio: true

    #fecha_nac:
    #  tipo: date
    #  obligatorio: false
    #edad:
    #  tipo: int
    #  obligatorio: true
    #  min: 18
    #genero:
    #  tipo: str
    #  obligatorio: true
    # valores: ['M', 'F']

reporte_errores:
  color_error_total: "FFCCCC"
  color_error_campo: "FFA500"
  nombre_columna_errores: "Errores"
  ruta_salida: "reporte_errores.xlsx"


# UI
interfaz:
  tema: claro
  ancho_ventana: 800
  alto_ventana: 600