app:
  autor: TuNombre
  idioma: es
  logs_dir: ./logs
  nombre: Form Auto Filler
  output_dir: ./reportes
  version: 1.0.0
interfaz:
  alto_ventana: 600
  ancho_ventana: 800
  tema: claro
reporte_errores:
  color_error_campo: FFA500
  color_error_total: FFCCCC
  nombre_columna_errores: Errores
  ruta_salida: reporte_errores.xlsx
selenium:
  headless: false
  maximizar: true
  navegador: chrome
  timeout: 10
  url_formulario: https://demoqa.com/text-box
validacion:
  archivo_excel: /home/frodinsky/PycharmProjects/Selenium-con-Python-Test-Qa-Automation/Manejar_Excel/datos.xlsx
  campos:
    dir0:
      obligatorio: true
      tipo: str
    dir1:
      obligatorio: true
      tipo: str
    email:
      obligatorio: true
      regex: ^\S+@\S+\.\S+$
      tipo: str
    nombre:
      obligatorio: true
      tipo: str
